import { describe, expect, it } from "vitest";
import { $ERROR_CODES, mapToErrorCode, type StreamPayErrorCode } from "../src/error-codes";

const EXPECTED_MAPPINGS: Array<[string, StreamPayErrorCode]> = [
	["INVALID_PARAMETERS", "VALIDATION_ERROR"],
	["PERMISSION_FORBIDDEN", "FORBIDDEN"],
	["BRANCH_ACCESS_DENIED", "FORBIDDEN"],
	["BRANCH_NOT_FOUND", "NOT_FOUND"],
	["DUPLICATE_CONSUMER", "CONSUMER_DUPLICATE"],
	["DUPLICATE_CARD_TOKEN", "CONSUMER_DUPLICATE"],
	["CONSUMER_HAS_ONGOING_INVOICES", "CONSUMER_HAS_ONGOING_ACTIVITY"],
	["CONSUMER_HAS_ONGOING_SUBSCRIPTIONS", "CONSUMER_HAS_ONGOING_ACTIVITY"],
	["INVOICE_FINALISED", "INVOICE_INVALID_STATE"],
	["INVOICE_INVALID_STATUS", "INVOICE_INVALID_STATE"],
	["INVOICE_CONSENT_CONSUMED", "INVOICE_INVALID_STATE"],
	["INVOICE_CONSENT_EXPIRED", "INVOICE_INVALID_STATE"],
	["INVOICE_TOTAL_MISMATCH_PAYMENT_AMOUNT_SUM", "INVOICE_INVALID_STATE"],
	["INVOICE_PAYMENT_COUNT_NOT_MATCHED", "INVOICE_INVALID_STATE"],
	["DUPLICATE_PAYMENT", "PAYMENT_DUPLICATE"],
	["PAYMENT_IN_PROGRESS", "PAYMENT_INVALID_STATE"],
	["PAYMENT_FINALIZED", "PAYMENT_INVALID_STATE"],
	["PAYMEND_UNPAID", "PAYMENT_INVALID_STATE"],
	["INVALID_STATUS", "PAYMENT_INVALID_STATE"],
	["PAYMENT_REFUNDED_ALREADY", "PAYMENT_ALREADY_REFUNDED"],
	["PAYMENT_REFUNDED_FAILED", "PAYMENT_REFUND_FAILED"],
	["PAYMENT_GATEWAY_DECLINED", "PAYMENT_GATEWAY_DECLINED"],
	["INSUFFICIENT_FUNDS", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_PAYMENT_INFO_MISMATCH", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_BAD_REQUEST", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_UNAUTHORIZED", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_FORBIDDEN", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_NOT_FOUND", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_METHOD_NOT_ALLOWED", "PAYMENT_GATEWAY_DECLINED"],
	["MOYASAR_TIMEOUT", "PAYMENT_GATEWAY_UNAVAILABLE"],
	["MOYASAR_TOO_MANY_REQUESTS", "PAYMENT_GATEWAY_UNAVAILABLE"],
	["MOYASAR_INTERNAL_SERVER_ERROR", "PAYMENT_GATEWAY_UNAVAILABLE"],
	["MOYASAR_SERVICE_UNAVAILABLE", "PAYMENT_GATEWAY_UNAVAILABLE"],
	["MOYASAR_INVALID_CARD_TOKEN", "PAYMENT_METHOD_INVALID"],
	["MANUAL_INVOICE_CARD_ID", "PAYMENT_METHOD_INVALID"],
	["ONE_OFF_INVALID_PAYMENT_FLOW", "PAYMENT_METHOD_INVALID"],
	["ONE_OFF_CARD_ID", "PAYMENT_METHOD_INVALID"],
	["AUTO_INVOICE_MISSING_CARD_ID", "PAYMENT_METHOD_INVALID"],
	["PAYMENT_FLOW_NOT_ALLOWED", "PAYMENT_METHOD_INVALID"],
	["PRODUCT_USED_IN_FINALIZED_INVOICE", "PRODUCT_LOCKED"],
	["COUPON_USED_IN_FINALIZED_INVOICE", "COUPON_LOCKED"],
	["SUBSCRIPTION_ALREADY_ACTIVE", "SUBSCRIPTION_ALREADY_ACTIVE"],
	["SUBSCRIPTION_NOT_FOUND", "SUBSCRIPTION_NOT_FOUND"],
	["SUBSCRIPTION_ALREADY_CANCELED", "SUBSCRIPTION_ALREADY_CANCELED"],
	["SUBSCRIPTION_ALREADY_FROZEN", "SUBSCRIPTION_ALREADY_FROZEN"],
	["SUBSCRIPTION_NOT_FROZEN", "SUBSCRIPTION_FREEZE_NOT_ACTIVE"],
	["SUBSCRIPTION_EXPIRED", "SUBSCRIPTION_EXPIRED"],
];

describe("mapToErrorCode — raw-code table", () => {
	it.each(EXPECTED_MAPPINGS)("maps %s → %s", (raw, expected) => {
		expect(mapToErrorCode(raw, undefined)).toBe(expected);
	});
});

describe("mapToErrorCode — status fallback", () => {
	it("falls back to UNAUTHORIZED on 401 with no raw code", () => {
		expect(mapToErrorCode(undefined, 401)).toBe("UNAUTHORIZED");
	});
	it("falls back to FORBIDDEN on 403 with no raw code", () => {
		expect(mapToErrorCode(undefined, 403)).toBe("FORBIDDEN");
	});
	it("falls back to NOT_FOUND on 404 with no raw code", () => {
		expect(mapToErrorCode(undefined, 404)).toBe("NOT_FOUND");
	});
	it("falls back to VALIDATION_ERROR on 422 with no raw code", () => {
		expect(mapToErrorCode(undefined, 422)).toBe("VALIDATION_ERROR");
	});
	it("returns UNKNOWN on unmapped status with no raw code", () => {
		expect(mapToErrorCode(undefined, 500)).toBe("UNKNOWN");
		expect(mapToErrorCode(undefined, undefined)).toBe("UNKNOWN");
	});
	it("returns UNKNOWN when the raw code is unrecognized and status is unmapped", () => {
		expect(mapToErrorCode("NEVER_HEARD_OF_IT", 500)).toBe("UNKNOWN");
	});
	it("prefers the raw-code mapping over the status classifier", () => {
		expect(mapToErrorCode("DUPLICATE_CONSUMER", 409)).toBe("CONSUMER_DUPLICATE");
	});
});

describe("$ERROR_CODES shape (Better Auth compatibility)", () => {
	it("exposes each code as { code, message, toString } (defineErrorCodes convention)", () => {
		expect($ERROR_CODES.VALIDATION_ERROR.code).toBe("VALIDATION_ERROR");
		expect(typeof $ERROR_CODES.VALIDATION_ERROR.message).toBe("string");
		expect(String($ERROR_CODES.VALIDATION_ERROR)).toBe("VALIDATION_ERROR");
	});

	it("every mapped bucket references a real $ERROR_CODES key", () => {
		for (const [, bucket] of EXPECTED_MAPPINGS) {
			expect($ERROR_CODES).toHaveProperty(bucket);
		}
	});
});
